version: '3.8'

services:
  markitdown-api:
    image: uitadmin/markitdown-api:latest
    container_name: markitdown-api
    ports:
      - "8000:8000"
    env_file:
      - docker_apikeys.env
    volumes:
      # Persist extracted images (required for image processing)
      - ./markitdown/images:/static/images
      # Optional: persist uploads directory
      - ./markitdown/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
